### ISSUE TITLE
Additional Pixel Formats

### ISSUE THREAD

**Issue by brinsche-fkt42** [Goddchen/dart-rfb#20]
Hey, thanks for the useful library so far! 
Are there any plans for supporting more pixel formats?
I'm trying to connect to a device which seems to default to `rgb565`(?)

Logging from connecting to the device:
`RemoteFrameBufferPixelFormat(bitsPerPixel: 16, depth: 16, bigEndian: false, trueColor: true, redMax: 31, greenMax: 63, blueMax: 31, redShift: 11, greenShift: 5, blueShift: 0)`

and it doesn't seem to support or respect setting the pixelformat to `bgra8888`, judging from logging when connecting with the tigervnc viewer `rgb888` is also supported.

How much work do you think it would be support either of those/more pixelformats? Ideally with support for decoding in flutter_rfb. 
I've looked into decoding and something like this https://stackoverflow.com/a/51316489 may be helpful for working around the fact that flutter only natively has support for `rgba8888` and `bgra8888`.

Also are there any plans for supporting ZRLE encoding?

**Comment by Goddchen** [comment]
Hi!

I haven't found any of the other pixel formats in the wild yet. That's why I didn't add them until now.

Adding them should not be complex. Just mapping bytes differently to the already existing data structures. Depending on how urgent this is for you, feel free to create a PR and I'll happily help in getting it released. I don't think I'll come to do it myself in the next 1 or 2 weeks.

**Comment by Goddchen** [comment]
ZRLE encoding: haven't had the time to implement it yet and since the `raw` encoding is a mandatory fall back, that every server has to support, I haven't implemented it so far. Feel free to create a PR if this is an urgent feature that need asap.
