### ISSUE TITLE
Discuss using `package:binary` v4 (& resulting breaking changes)

### ISSUE THREAD

**Issue by matanlurey** [Goddchen/dart-rfb#24]
Hey there!

I'm in the process of proposing the next version of [`package:binary`](https://pub.dev/packages/binary/versions/4.0.0-alpha+7), which uses extension types is a fairly large breaking change as a result. I think your package is the most popular on pub.dev that uses it, so I wanted to give you the chance to provide feedback (should we provide compatibility APIs to ease upgrading? are the new APIs sensible?).

Take your time - I'm not in a rush to publish v4 stable.

~ Matan

**Comment by Goddchen** [comment]
@matanlurey  Thanks for letting me know and sorry for the late reply. Since it is a major version jump, I would expect there to be breaking changes. So I wouldn't expect to "compat" classes or something like that.

I only had to update the use of `setBit(...)` to `setNthBit(...)`, easy.

See https://github.com/Goddchen/dart-rfb/pull/27

**Comment by matanlurey** [comment]
Great, thanks!
